# Generated by Django 5.1.3 on 2024-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activation_token",
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
