# Generated by Django 5.1.3 on 2024-12-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activation_token",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True, unique=True
            ),
        ),
    ]
