# Generated by Django 5.1.3 on 2024-12-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_activation_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="activation_token",
        ),
    ]
