# Generated by Django 5.1.3 on 2024-12-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customuser_activation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
