# Generated by Django 5.1.3 on 2025-01-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="questions",
            field=models.ManyToManyField(
                related_name="assessments", to="assessments.question"
            ),
        ),
    ]
