# Generated by Django 5.1.3 on 2024-12-31 11:03

import edugen_tutor_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edugen_tutor_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a subject cover image (max 5MB)",
                null=True,
                upload_to="subjects/",
                validators=[edugen_tutor_model.models.validate_image_size],
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a topic cover image (max 5MB)",
                null=True,
                upload_to="topics/",
                validators=[edugen_tutor_model.models.validate_image_size],
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
